VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network :private_network, ip: "192.168.99.2"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = 'test_pyatomiadns.yml'
      ansible.verbose = 'extra'
  end
end
